package SomeInterviews.roblox;

import java.util.*;

public class ValidatePlaylistSequence {
    /*
    Validate Playlist Sequence
A music streaming service is analyzing user playback data to distinguish between two of its playback modes: Shuffle Mode and Random Mode. Your task is to determine if a given sequence of played songs could have been generated by Shuffle Mode.
Here's how the modes work:
Random Mode: The next song is chosen uniformly at random from the entire library. Songs can repeat at any time.
Shuffle Mode: The player first creates a random permutation of all unique songs in the library. It plays through this sequence one by one. Once every song has been played exactly once, it generates a new random permutation and continues.
You are given allSongs, a list of all unique songs in the library, and playlist, a sequence of songs a user listened to. You can assume the user might have started listening in the middle of a permutation and stopped at any time.
Return true if the playlist sequence could possibly be a contiguous subsequence from a Shuffle Mode playback. Otherwise, return false.
Constraints:
1 ≤ allSongs.length ≤ 100
1 ≤ playlist.length ≤ 100
All elements of allSongs are unique non-empty strings.
All elements of playlist are present in allSongs.
Example 1:
Input: allSongs = ["A", "B", "C"], playlist = ["A", "B", "C", "A", "C", "B"]
Output: true
Explanation: This sequence can be partitioned into two complete, valid permutations:
The first part, ["A", "B", "C"], contains all unique songs exactly once.
The second part, ["A", "C", "B"], is another valid permutation.
Because the entire listening history conforms to the rules of shuffle mode, the output is true.
Example 2:
Input: allSongs = ["A", "B", "C"], playlist = ["A", "B", "C", "C"]
Output: true
Example 3:
Input: allSongs = ["A", "B", "C"], playlist = ["A", "B", "C", "C", "C"]
Output: false

     */
    //只要遍历listened里面，确保每个歌出现不多于1，如果出现了2次，那么肯定是完成了第一轮，即出现了所有的首歌，因此用一个count代表所有歌，结合出现次数判断
    public boolean isShuffle(List<String> songs, List<String> listened){
        Set<String> set=new HashSet<>(songs);

        int count=set.size();
        for (String s:listened){
            if(set.contains(s)){
                set.remove(s);
                count--;
                if(count==0){
                    set=new HashSet<>(songs);
                    count=set.size();
                }
            }else{
                return false;
            }
        }

        return true;
    }
    //这是答案，更好一点吧，不需要每次都新建set，只要clear就行了
    public boolean isPossibleShuffle2(List<String> allSongs, List<String> playlist) {
        if (playlist.isEmpty())
            return true;

        Set<String> set = new HashSet<>();

        for (String song : playlist) {
            if (set.contains(song)) {
                return false;
            }

            set.add(song);

            // If we've completed a full permutation, reset for next one
            if (set.size() == allSongs.size()) {
                set.clear();
            }
        }

        return true;
    }


}
